local global = vim.g
local o = vim.opt

-- Editor options

o.number = true -- Print the line number in front of each line
o.relativenumber = true -- Show the line number relative to the line with the cursor in front of each line.
o.clipboard = "unnamedplus" -- uses the clipboard register for all operations except yank.
o.syntax = "on" -- When this option is set, the syntax with this name is loaded.
o.autoindent = true -- Copy indent from current line when starting a new line.
o.cursorline = true -- Highlight the screen line of the cursor with CursorLine.
o.ruler = true -- Show the line and column number of the cursor position, separated by a comma.
o.mouse = "" -- Enable the use of the mouse. "a" you can use on all modes
o.title = true -- When on, the title of the window will be set to the value of 'titlestring'
o.ttimeoutlen = 300 -- The time in milliseconds that is waited for a key code or mapped key sequence to complete.
o.wildmenu = true -- When 'wildmenu' is on, command-line completion operates in an enhanced mode.
o.showcmd = true -- Show (partial) command in the last line of the screen. Set this option off if your terminal is slow.
o.showmatch = true -- When a bracket is inserted, briefly jump to the matching one.
o.inccommand = "split" -- When nonempty, shows the effects of :substitute, :smagic, :snomagic and user commands with the :command-preview flag as you typ
o.splitright = true
o.splitbelow = true -- When on, splitting a window will put the new window below the current one
o.termguicolors = true
o.wrap = false -- Zeilenumbruch deaktivieren
o.sidescroll = 1      -- Scrollt horizontal, sobald nötig
o.sidescrolloff = 5   -- Hält 5 Zeichen Puffer beim Scrollen
o.scrolloff = 5   -- Hält 5 Zeichen Puffer beim Scrollen
o.laststatus = 3
o.splitkeep = "topline"
o.fillchars = "eob: ,vert:│,fold: "
o.mouse = "a"
global.neovide_cursor_animation_length = 0.05
global.neovide_cursor_vfx_opacity = 0
global.neovide_cursor_trail_size = 0
global.neovide_refresh_rate = 60
o.termguicolors = true
vim.env.PATH = vim.env.PATH .. ";" .. "C:\\Program Files\\nodejs"
o.expandtab = false  -- Echte Tabs verwenden
o.tabstop = 4
o.shiftwidth = 4
o.softtabstop = 4
